# Budget justification

> 3 Pages

> Proposals must include a proposed budget, which will detail the specific expenses for which the award funds will be used, including any costs associated with research materials or equipment, research assistance, or travel. Proposed budgets should also include an expected timeline for expenditures and indicate whether the research scholar expects the grant to be active for one year or two years.

> APSA Doctoral Dissertation Improvement Grants will cover only direct costs for research activities. The grant is not intended to provide the full costs of a student's doctoral dissertation research. Project budgets should be developed at scales appropriate for the work to be conducted and may only include costs directly associated with the conduct of dissertation research. For APSA grants, overhead or indirect costs are not considered allowable expenses.

> The grant is intended to provide funding for research costs not normally covered by the grantee's university. Examples of the kinds of expenses that may be included in a proposal budget are the following:

  
- costs for data-collection activities, including the conduct of surveys, questionnaires, and/or focus groups or the -purchase of extant data  
- costs for equipment necessary for the conduct of the project that will be devoted to the project over the duration of the award  
- costs for payments to research subjects and/or informants
- analysis and research services not otherwise available

> Along with the proposed budget itself, proposals must include a budget justification, explaining and justifying each budget line. The budget justification should be no longer than three pages single spaced.

\newpage