# Data management plan

> ~~No longer than 2 pages, single-spaced~~ 1000 words

> Proposals will require a data management plan that describes the data that will be generated by the research, how the data will be managed, secured, and shared, and other pertinent information about the content and handling of the data. 

*Data, software, and other materials to be produced in the course of the project*


Documentation on how to use the software and access the data will be avaiable on GitHub. 

*Standards to be used for data and metadata format and content*

All datasets will be available in .Rdata and SQL format. 

*Policies for access and sharing*

All data  will be publically available on GitHub. 

Both R packages will be hosted as public repositories on GitHub so that anyone can contribute to their source code.

*Policies and provisions for re-use, re-distribution, and the production of derivatives*

All data and R packages created through this project will be avaible for re-use under the Geneal Public License, GPL-3 standard.

*Plans for archiving data, samples, and other research products, and for preservation of access to them*

Both R packages and most data will be available on GitHub.com.

\newpage

